### ISSUE TITLE
Incompatible with idris 1.3

### ISSUE THREAD

**Issue by doofin** [be5invis/idris-codegen-js#1]
Loading ././Main.ibc failed: Incompatible ibc version for: "././Main.ibc"
This module was built with a later version of Idris.
Please clean and rebuild.

Uncaught error: Elaborating {__infer_0} arg {ival_0}: NoSuchVariable run__IO

**Comment by imuli** [comment]
This currently doesn't compile against Idris 1.3 either.

**Comment by be5invis** [comment]
To be honest Idris Official has already adopted my codegen, with even better performance.

**Comment by imuli** [comment]
I was just about to go and do performance comparisons - thanks.
